#!/usr/bin/env node
var Nightmare = require('nightmare');
var nightmare = Nightmare();

nightmare
  .goto('https://translate.google.com')
  .wait('#gt-sl-sugg > div[value="auto"]')
  .click('#gt-sl-sugg > div[value="auto"]')
  .insert('#source', process.argv[2])
  .click('#gt-submit')
  .wait('#result_box > span')
  .evaluate(function () {
    return document.querySelector('#result_box').innerHTML.replace(/<\/*span>/g, '');
  })
  .end()
  .then(function (result) {
    console.log(result)
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
